-- Batch 4.5 RLS policies for the 5 new resources added in
-- 20260526024321_batch_4_5_schema_extensions. Generated by:
--   pnpm tsx scripts/generate-rls-sql.ts > /tmp/rls_full.sql
-- then filtered to the new tables only. Existing tables already have
-- RLS applied via 20260523030651_apply_rls_policies +
-- 20260525085230_add_investment_phase_rls.

-- RLS policies for "public"."amortization_rule" (matrix resource: "amortization_rule")

ALTER TABLE "public"."amortization_rule" ENABLE ROW LEVEL SECURITY;

-- MASTER bypass: a permissive policy granting full access when the JWT's role is MASTER.
DROP POLICY IF EXISTS "amortization_rule_master_bypass" ON "public"."amortization_rule";
CREATE POLICY "amortization_rule_master_bypass" ON "public"."amortization_rule"
  AS PERMISSIVE FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER');

-- CREATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "amortization_rule_create" ON "public"."amortization_rule";
CREATE POLICY "amortization_rule_create" ON "public"."amortization_rule"
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- READ: allowed for CEO, ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "amortization_rule_read" ON "public"."amortization_rule";
CREATE POLICY "amortization_rule_read" ON "public"."amortization_rule"
  AS PERMISSIVE FOR SELECT TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('CEO', 'ANALISTA', 'AUXILIAR'));

-- UPDATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "amortization_rule_update" ON "public"."amortization_rule";
CREATE POLICY "amortization_rule_update" ON "public"."amortization_rule"
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- DELETE: allowed for ANALISTA.
DROP POLICY IF EXISTS "amortization_rule_delete" ON "public"."amortization_rule";
CREATE POLICY "amortization_rule_delete" ON "public"."amortization_rule"
  AS PERMISSIVE FOR DELETE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- RLS policies for "public"."partner_contribution" (matrix resource: "partner_contribution")

ALTER TABLE "public"."partner_contribution" ENABLE ROW LEVEL SECURITY;

-- MASTER bypass: a permissive policy granting full access when the JWT's role is MASTER.
DROP POLICY IF EXISTS "partner_contribution_master_bypass" ON "public"."partner_contribution";
CREATE POLICY "partner_contribution_master_bypass" ON "public"."partner_contribution"
  AS PERMISSIVE FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER');

-- CREATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "partner_contribution_create" ON "public"."partner_contribution";
CREATE POLICY "partner_contribution_create" ON "public"."partner_contribution"
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- READ: allowed for CEO, ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "partner_contribution_read" ON "public"."partner_contribution";
CREATE POLICY "partner_contribution_read" ON "public"."partner_contribution"
  AS PERMISSIVE FOR SELECT TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('CEO', 'ANALISTA', 'AUXILIAR'));

-- UPDATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "partner_contribution_update" ON "public"."partner_contribution";
CREATE POLICY "partner_contribution_update" ON "public"."partner_contribution"
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- DELETE: allowed for ANALISTA.
DROP POLICY IF EXISTS "partner_contribution_delete" ON "public"."partner_contribution";
CREATE POLICY "partner_contribution_delete" ON "public"."partner_contribution"
  AS PERMISSIVE FOR DELETE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- RLS policies for "public"."contribution_source" (matrix resource: "contribution_source")

ALTER TABLE "public"."contribution_source" ENABLE ROW LEVEL SECURITY;

-- MASTER bypass: a permissive policy granting full access when the JWT's role is MASTER.
DROP POLICY IF EXISTS "contribution_source_master_bypass" ON "public"."contribution_source";
CREATE POLICY "contribution_source_master_bypass" ON "public"."contribution_source"
  AS PERMISSIVE FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER');

-- CREATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "contribution_source_create" ON "public"."contribution_source";
CREATE POLICY "contribution_source_create" ON "public"."contribution_source"
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- READ: allowed for CEO, ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "contribution_source_read" ON "public"."contribution_source";
CREATE POLICY "contribution_source_read" ON "public"."contribution_source"
  AS PERMISSIVE FOR SELECT TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('CEO', 'ANALISTA', 'AUXILIAR'));

-- UPDATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "contribution_source_update" ON "public"."contribution_source";
CREATE POLICY "contribution_source_update" ON "public"."contribution_source"
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- DELETE: allowed for ANALISTA.
DROP POLICY IF EXISTS "contribution_source_delete" ON "public"."contribution_source";
CREATE POLICY "contribution_source_delete" ON "public"."contribution_source"
  AS PERMISSIVE FOR DELETE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- RLS policies for "public"."isr_obligation" (matrix resource: "isr_obligation")

ALTER TABLE "public"."isr_obligation" ENABLE ROW LEVEL SECURITY;

-- MASTER bypass: a permissive policy granting full access when the JWT's role is MASTER.
DROP POLICY IF EXISTS "isr_obligation_master_bypass" ON "public"."isr_obligation";
CREATE POLICY "isr_obligation_master_bypass" ON "public"."isr_obligation"
  AS PERMISSIVE FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER');

-- CREATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "isr_obligation_create" ON "public"."isr_obligation";
CREATE POLICY "isr_obligation_create" ON "public"."isr_obligation"
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- READ: allowed for CEO, ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "isr_obligation_read" ON "public"."isr_obligation";
CREATE POLICY "isr_obligation_read" ON "public"."isr_obligation"
  AS PERMISSIVE FOR SELECT TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('CEO', 'ANALISTA', 'AUXILIAR'));

-- UPDATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "isr_obligation_update" ON "public"."isr_obligation";
CREATE POLICY "isr_obligation_update" ON "public"."isr_obligation"
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- DELETE: allowed for ANALISTA.
DROP POLICY IF EXISTS "isr_obligation_delete" ON "public"."isr_obligation";
CREATE POLICY "isr_obligation_delete" ON "public"."isr_obligation"
  AS PERMISSIVE FOR DELETE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- RLS policies for "public"."data_quality_flag" (matrix resource: "data_quality_flag")

ALTER TABLE "public"."data_quality_flag" ENABLE ROW LEVEL SECURITY;

-- MASTER bypass: a permissive policy granting full access when the JWT's role is MASTER.
DROP POLICY IF EXISTS "data_quality_flag_master_bypass" ON "public"."data_quality_flag";
CREATE POLICY "data_quality_flag_master_bypass" ON "public"."data_quality_flag"
  AS PERMISSIVE FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER');

-- CREATE: no non-MASTER role allowed by the matrix.
DROP POLICY IF EXISTS "data_quality_flag_create_deny" ON "public"."data_quality_flag";
-- (No CREATE POLICY emitted; absence of a permissive policy implicitly denies.)

-- READ: allowed for CEO, ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "data_quality_flag_read" ON "public"."data_quality_flag";
CREATE POLICY "data_quality_flag_read" ON "public"."data_quality_flag"
  AS PERMISSIVE FOR SELECT TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('CEO', 'ANALISTA', 'AUXILIAR'));

-- UPDATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "data_quality_flag_update" ON "public"."data_quality_flag";
CREATE POLICY "data_quality_flag_update" ON "public"."data_quality_flag"
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- DELETE: allowed for ANALISTA.
DROP POLICY IF EXISTS "data_quality_flag_delete" ON "public"."data_quality_flag";
CREATE POLICY "data_quality_flag_delete" ON "public"."data_quality_flag"
  AS PERMISSIVE FOR DELETE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

