/**
 * Markdown report generator for parity results.
 *
 * Output format matches the deliverable in PLAN.md Batch 18:
 *   "every SDD number, the app's number, delta, pass/fail"
 *
 * Header carries: timestamp, total/pass/fail, per-category summary.
 * Body: one section per category with a markdown table.
 */

import type { AssertionResult } from "./assertions";
import type { ResultSummary } from "./runner";

export function renderMarkdownReport(
  results: AssertionResult[],
  summary: ResultSummary,
  generatedAt: Date,
): string {
  const lines: string[] = [];
  lines.push("# Batch 18 — End-to-end Parity Report");
  lines.push("");
  lines.push(
    "Generated by `pnpm parity:report`. Source of truth for assertions:",
  );
  lines.push("`scripts/parity/assertions.ts`. Do not hand-edit this file — re-run the");
  lines.push("script to regenerate.");
  lines.push("");
  lines.push(`- **Generated:** ${generatedAt.toISOString()}`);
  lines.push(`- **Total assertions:** ${summary.total}`);
  lines.push(
    `- **Passed:** ${summary.passed} · **Failed:** ${summary.failed} · **Pass rate:** ${
      summary.total === 0 ? "n/a" : ((summary.passed / summary.total) * 100).toFixed(1) + "%"
    }`,
  );
  lines.push("");

  // ── Per-category summary ────────────────────────────────────────────
  lines.push("## Summary by category");
  lines.push("");
  lines.push("| Category | Total | Passed | Failed |");
  lines.push("| --- | ---: | ---: | ---: |");
  for (const c of summary.byCategory) {
    lines.push(`| ${c.category} | ${c.total} | ${c.passed} | ${c.failed} |`);
  }
  lines.push("");

  // ── Per-category details ────────────────────────────────────────────
  const grouped = new Map<string, AssertionResult[]>();
  for (const r of results) {
    const arr = grouped.get(r.category) ?? [];
    arr.push(r);
    grouped.set(r.category, arr);
  }
  for (const [category, rs] of grouped) {
    lines.push(`## ${category}`);
    lines.push("");
    lines.push(
      "| # | Assertion | SDD ref | Expected | Actual | Δ | Tol | Pass |",
    );
    lines.push("| --- | --- | --- | --- | --- | --- | --- | :---: |");
    rs.forEach((r, i) => {
      const icon = r.pass ? "✓" : "✗";
      const tol = r.tolerance === 0 ? "exact" : `±${r.tolerance}`;
      const errSuffix = r.error != null ? ` ⚠ ${escapePipe(r.error)}` : "";
      lines.push(
        `| ${i + 1} | ${escapePipe(r.description)}${errSuffix} | ${escapePipe(r.sddRef)} | \`${r.expected}\` | \`${r.actual}\` | \`${r.delta}\` | ${tol} | ${icon} |`,
      );
    });
    lines.push("");
  }

  if (summary.failed > 0) {
    lines.push("## Failures (full detail)");
    lines.push("");
    for (const r of results.filter((x) => !x.pass)) {
      lines.push(`### ✗ \`${r.id}\` — ${r.description}`);
      lines.push("");
      lines.push(`- **SDD ref:** ${r.sddRef}`);
      lines.push(`- **Expected:** \`${r.expected}\``);
      lines.push(`- **Actual:** \`${r.actual}\``);
      lines.push(`- **Δ:** \`${r.delta}\` (tolerance ${r.tolerance === 0 ? "exact" : `±${r.tolerance}`})`);
      if (r.error != null) lines.push(`- **Error:** ${r.error}`);
      lines.push("");
    }
  }

  return lines.join("\n");
}

function escapePipe(s: string): string {
  return s.replace(/\|/g, "\\|");
}
