/**
 * Generate RLS-policy SQL for every resource in the matrix.
 *
 * Prints SQL to stdout. Pipe into the corresponding Prisma migration:
 *
 *   pnpm tsx scripts/generate-rls-sql.ts > prisma/migrations/<ts>_apply_rls_policies/migration.sql
 *
 * Re-run whenever `src/lib/rbac/matrix.ts` changes; create a new migration
 * for the diff (don't mutate an applied migration in place).
 */

import { MATRIX } from "../src/lib/rbac/matrix";
import { buildPolicySqlForAll } from "../src/lib/rbac/policies";

// Every resource in the matrix maps 1:1 to a Postgres table of the same name.
// This is intentional: keeping the matrix keys snake_case-aligned with the
// schema's `@@map(...)` table names lets the generator pass `resource`
// straight through to RLS SQL without a translation table.
const tables = Object.keys(MATRIX).map((resource) => ({
  resource,
  tableName: resource,
}));

const sql = buildPolicySqlForAll({ matrix: MATRIX, tables });

process.stdout.write(
  [
    "-- ─────────────────────────────────────────────────────────────────────",
    "-- Row-Level Security policies for the Santa Elena RBAC matrix.",
    "-- Generated by `pnpm tsx scripts/generate-rls-sql.ts`. Do not hand-edit;",
    "-- re-run the generator after changing `src/lib/rbac/matrix.ts`.",
    "-- The matrix's source of truth lives in TypeScript; this file is the",
    "-- DB-layer mirror.",
    "-- ─────────────────────────────────────────────────────────────────────",
    "",
    sql,
  ].join("\n"),
);
