-- ─────────────────────────────────────────────────────────────────────
-- Row-Level Security policies for the Santa Elena RBAC matrix.
-- Generated by `pnpm tsx scripts/generate-rls-sql.ts`. Do not hand-edit;
-- re-run the generator after changing `src/lib/rbac/matrix.ts`.
-- The matrix's source of truth lives in TypeScript; this file is the
-- DB-layer mirror.
-- ─────────────────────────────────────────────────────────────────────

-- RLS policies for "public"."project" (matrix resource: "project")
ALTER TABLE "public"."project" ENABLE ROW LEVEL SECURITY;

-- MASTER bypass: a permissive policy granting full access when the JWT's role is MASTER.
DROP POLICY IF EXISTS "project_master_bypass" ON "public"."project";
CREATE POLICY "project_master_bypass" ON "public"."project"
  AS PERMISSIVE FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER');

-- CREATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "project_create" ON "public"."project";
CREATE POLICY "project_create" ON "public"."project"
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- READ: allowed for CEO, ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "project_read" ON "public"."project";
CREATE POLICY "project_read" ON "public"."project"
  AS PERMISSIVE FOR SELECT TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('CEO', 'ANALISTA', 'AUXILIAR'));

-- UPDATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "project_update" ON "public"."project";
CREATE POLICY "project_update" ON "public"."project"
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- DELETE: allowed for ANALISTA.
DROP POLICY IF EXISTS "project_delete" ON "public"."project";
CREATE POLICY "project_delete" ON "public"."project"
  AS PERMISSIVE FOR DELETE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- RLS policies for "public"."users" (matrix resource: "users")
ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;

-- MASTER bypass: a permissive policy granting full access when the JWT's role is MASTER.
DROP POLICY IF EXISTS "users_master_bypass" ON "public"."users";
CREATE POLICY "users_master_bypass" ON "public"."users"
  AS PERMISSIVE FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER');

-- CREATE: no non-MASTER role allowed by the matrix.
DROP POLICY IF EXISTS "users_create_deny" ON "public"."users";
-- (No CREATE POLICY emitted; absence of a permissive policy implicitly denies.)

-- READ: no non-MASTER role allowed by the matrix.
DROP POLICY IF EXISTS "users_read_deny" ON "public"."users";
-- (No CREATE POLICY emitted; absence of a permissive policy implicitly denies.)

-- UPDATE: no non-MASTER role allowed by the matrix.
DROP POLICY IF EXISTS "users_update_deny" ON "public"."users";
-- (No CREATE POLICY emitted; absence of a permissive policy implicitly denies.)

-- DELETE: no non-MASTER role allowed by the matrix.
DROP POLICY IF EXISTS "users_delete_deny" ON "public"."users";
-- (No CREATE POLICY emitted; absence of a permissive policy implicitly denies.)

-- RLS policies for "public"."partner" (matrix resource: "partner")
ALTER TABLE "public"."partner" ENABLE ROW LEVEL SECURITY;

-- MASTER bypass: a permissive policy granting full access when the JWT's role is MASTER.
DROP POLICY IF EXISTS "partner_master_bypass" ON "public"."partner";
CREATE POLICY "partner_master_bypass" ON "public"."partner"
  AS PERMISSIVE FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER');

-- CREATE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "partner_create" ON "public"."partner";
CREATE POLICY "partner_create" ON "public"."partner"
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- READ: allowed for CEO, ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "partner_read" ON "public"."partner";
CREATE POLICY "partner_read" ON "public"."partner"
  AS PERMISSIVE FOR SELECT TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('CEO', 'ANALISTA', 'AUXILIAR'));

-- UPDATE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "partner_update" ON "public"."partner";
CREATE POLICY "partner_update" ON "public"."partner"
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- DELETE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "partner_delete" ON "public"."partner";
CREATE POLICY "partner_delete" ON "public"."partner"
  AS PERMISSIVE FOR DELETE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- RLS policies for "public"."bank_account" (matrix resource: "bank_account")
ALTER TABLE "public"."bank_account" ENABLE ROW LEVEL SECURITY;

-- MASTER bypass: a permissive policy granting full access when the JWT's role is MASTER.
DROP POLICY IF EXISTS "bank_account_master_bypass" ON "public"."bank_account";
CREATE POLICY "bank_account_master_bypass" ON "public"."bank_account"
  AS PERMISSIVE FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER');

-- CREATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "bank_account_create" ON "public"."bank_account";
CREATE POLICY "bank_account_create" ON "public"."bank_account"
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- READ: allowed for CEO, ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "bank_account_read" ON "public"."bank_account";
CREATE POLICY "bank_account_read" ON "public"."bank_account"
  AS PERMISSIVE FOR SELECT TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('CEO', 'ANALISTA', 'AUXILIAR'));

-- UPDATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "bank_account_update" ON "public"."bank_account";
CREATE POLICY "bank_account_update" ON "public"."bank_account"
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- DELETE: allowed for ANALISTA.
DROP POLICY IF EXISTS "bank_account_delete" ON "public"."bank_account";
CREATE POLICY "bank_account_delete" ON "public"."bank_account"
  AS PERMISSIVE FOR DELETE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- RLS policies for "public"."budget_execution_partition" (matrix resource: "budget_execution_partition")
ALTER TABLE "public"."budget_execution_partition" ENABLE ROW LEVEL SECURITY;

-- MASTER bypass: a permissive policy granting full access when the JWT's role is MASTER.
DROP POLICY IF EXISTS "budget_execution_partition_master_bypass" ON "public"."budget_execution_partition";
CREATE POLICY "budget_execution_partition_master_bypass" ON "public"."budget_execution_partition"
  AS PERMISSIVE FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER');

-- CREATE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "budget_execution_partition_create" ON "public"."budget_execution_partition";
CREATE POLICY "budget_execution_partition_create" ON "public"."budget_execution_partition"
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- READ: allowed for CEO, ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "budget_execution_partition_read" ON "public"."budget_execution_partition";
CREATE POLICY "budget_execution_partition_read" ON "public"."budget_execution_partition"
  AS PERMISSIVE FOR SELECT TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('CEO', 'ANALISTA', 'AUXILIAR'));

-- UPDATE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "budget_execution_partition_update" ON "public"."budget_execution_partition";
CREATE POLICY "budget_execution_partition_update" ON "public"."budget_execution_partition"
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- DELETE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "budget_execution_partition_delete" ON "public"."budget_execution_partition";
CREATE POLICY "budget_execution_partition_delete" ON "public"."budget_execution_partition"
  AS PERMISSIVE FOR DELETE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- RLS policies for "public"."budget_category" (matrix resource: "budget_category")
ALTER TABLE "public"."budget_category" ENABLE ROW LEVEL SECURITY;

-- MASTER bypass: a permissive policy granting full access when the JWT's role is MASTER.
DROP POLICY IF EXISTS "budget_category_master_bypass" ON "public"."budget_category";
CREATE POLICY "budget_category_master_bypass" ON "public"."budget_category"
  AS PERMISSIVE FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER');

-- CREATE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "budget_category_create" ON "public"."budget_category";
CREATE POLICY "budget_category_create" ON "public"."budget_category"
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- READ: allowed for CEO, ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "budget_category_read" ON "public"."budget_category";
CREATE POLICY "budget_category_read" ON "public"."budget_category"
  AS PERMISSIVE FOR SELECT TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('CEO', 'ANALISTA', 'AUXILIAR'));

-- UPDATE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "budget_category_update" ON "public"."budget_category";
CREATE POLICY "budget_category_update" ON "public"."budget_category"
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- DELETE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "budget_category_delete" ON "public"."budget_category";
CREATE POLICY "budget_category_delete" ON "public"."budget_category"
  AS PERMISSIVE FOR DELETE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- RLS policies for "public"."budget_sub_item" (matrix resource: "budget_sub_item")
ALTER TABLE "public"."budget_sub_item" ENABLE ROW LEVEL SECURITY;

-- MASTER bypass: a permissive policy granting full access when the JWT's role is MASTER.
DROP POLICY IF EXISTS "budget_sub_item_master_bypass" ON "public"."budget_sub_item";
CREATE POLICY "budget_sub_item_master_bypass" ON "public"."budget_sub_item"
  AS PERMISSIVE FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER');

-- CREATE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "budget_sub_item_create" ON "public"."budget_sub_item";
CREATE POLICY "budget_sub_item_create" ON "public"."budget_sub_item"
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- READ: allowed for CEO, ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "budget_sub_item_read" ON "public"."budget_sub_item";
CREATE POLICY "budget_sub_item_read" ON "public"."budget_sub_item"
  AS PERMISSIVE FOR SELECT TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('CEO', 'ANALISTA', 'AUXILIAR'));

-- UPDATE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "budget_sub_item_update" ON "public"."budget_sub_item";
CREATE POLICY "budget_sub_item_update" ON "public"."budget_sub_item"
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- DELETE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "budget_sub_item_delete" ON "public"."budget_sub_item";
CREATE POLICY "budget_sub_item_delete" ON "public"."budget_sub_item"
  AS PERMISSIVE FOR DELETE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- RLS policies for "public"."expenditure" (matrix resource: "expenditure")
ALTER TABLE "public"."expenditure" ENABLE ROW LEVEL SECURITY;

-- MASTER bypass: a permissive policy granting full access when the JWT's role is MASTER.
DROP POLICY IF EXISTS "expenditure_master_bypass" ON "public"."expenditure";
CREATE POLICY "expenditure_master_bypass" ON "public"."expenditure"
  AS PERMISSIVE FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER');

-- CREATE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "expenditure_create" ON "public"."expenditure";
CREATE POLICY "expenditure_create" ON "public"."expenditure"
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- READ: allowed for CEO, ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "expenditure_read" ON "public"."expenditure";
CREATE POLICY "expenditure_read" ON "public"."expenditure"
  AS PERMISSIVE FOR SELECT TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('CEO', 'ANALISTA', 'AUXILIAR'));

-- UPDATE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "expenditure_update" ON "public"."expenditure";
CREATE POLICY "expenditure_update" ON "public"."expenditure"
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- DELETE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "expenditure_delete" ON "public"."expenditure";
CREATE POLICY "expenditure_delete" ON "public"."expenditure"
  AS PERMISSIVE FOR DELETE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- RLS policies for "public"."rv_units" (matrix resource: "rv_units")
ALTER TABLE "public"."rv_units" ENABLE ROW LEVEL SECURITY;

-- MASTER bypass: a permissive policy granting full access when the JWT's role is MASTER.
DROP POLICY IF EXISTS "rv_units_master_bypass" ON "public"."rv_units";
CREATE POLICY "rv_units_master_bypass" ON "public"."rv_units"
  AS PERMISSIVE FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER');

-- CREATE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "rv_units_create" ON "public"."rv_units";
CREATE POLICY "rv_units_create" ON "public"."rv_units"
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- READ: allowed for CEO, ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "rv_units_read" ON "public"."rv_units";
CREATE POLICY "rv_units_read" ON "public"."rv_units"
  AS PERMISSIVE FOR SELECT TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('CEO', 'ANALISTA', 'AUXILIAR'));

-- UPDATE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "rv_units_update" ON "public"."rv_units";
CREATE POLICY "rv_units_update" ON "public"."rv_units"
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- DELETE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "rv_units_delete" ON "public"."rv_units";
CREATE POLICY "rv_units_delete" ON "public"."rv_units"
  AS PERMISSIVE FOR DELETE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- RLS policies for "public"."rv_reservations" (matrix resource: "rv_reservations")
ALTER TABLE "public"."rv_reservations" ENABLE ROW LEVEL SECURITY;

-- MASTER bypass: a permissive policy granting full access when the JWT's role is MASTER.
DROP POLICY IF EXISTS "rv_reservations_master_bypass" ON "public"."rv_reservations";
CREATE POLICY "rv_reservations_master_bypass" ON "public"."rv_reservations"
  AS PERMISSIVE FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER');

-- CREATE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "rv_reservations_create" ON "public"."rv_reservations";
CREATE POLICY "rv_reservations_create" ON "public"."rv_reservations"
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- READ: allowed for CEO, ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "rv_reservations_read" ON "public"."rv_reservations";
CREATE POLICY "rv_reservations_read" ON "public"."rv_reservations"
  AS PERMISSIVE FOR SELECT TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('CEO', 'ANALISTA', 'AUXILIAR'));

-- UPDATE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "rv_reservations_update" ON "public"."rv_reservations";
CREATE POLICY "rv_reservations_update" ON "public"."rv_reservations"
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- DELETE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "rv_reservations_delete" ON "public"."rv_reservations";
CREATE POLICY "rv_reservations_delete" ON "public"."rv_reservations"
  AS PERMISSIVE FOR DELETE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- RLS policies for "public"."rv_freeze_requests" (matrix resource: "rv_freeze_requests")
ALTER TABLE "public"."rv_freeze_requests" ENABLE ROW LEVEL SECURITY;

-- MASTER bypass: a permissive policy granting full access when the JWT's role is MASTER.
DROP POLICY IF EXISTS "rv_freeze_requests_master_bypass" ON "public"."rv_freeze_requests";
CREATE POLICY "rv_freeze_requests_master_bypass" ON "public"."rv_freeze_requests"
  AS PERMISSIVE FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER');

-- CREATE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "rv_freeze_requests_create" ON "public"."rv_freeze_requests";
CREATE POLICY "rv_freeze_requests_create" ON "public"."rv_freeze_requests"
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- READ: allowed for CEO, ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "rv_freeze_requests_read" ON "public"."rv_freeze_requests";
CREATE POLICY "rv_freeze_requests_read" ON "public"."rv_freeze_requests"
  AS PERMISSIVE FOR SELECT TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('CEO', 'ANALISTA', 'AUXILIAR'));

-- UPDATE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "rv_freeze_requests_update" ON "public"."rv_freeze_requests";
CREATE POLICY "rv_freeze_requests_update" ON "public"."rv_freeze_requests"
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- DELETE: allowed for ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "rv_freeze_requests_delete" ON "public"."rv_freeze_requests";
CREATE POLICY "rv_freeze_requests_delete" ON "public"."rv_freeze_requests"
  AS PERMISSIVE FOR DELETE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA', 'AUXILIAR'));

-- RLS policies for "public"."monthly_projection" (matrix resource: "monthly_projection")
ALTER TABLE "public"."monthly_projection" ENABLE ROW LEVEL SECURITY;

-- MASTER bypass: a permissive policy granting full access when the JWT's role is MASTER.
DROP POLICY IF EXISTS "monthly_projection_master_bypass" ON "public"."monthly_projection";
CREATE POLICY "monthly_projection_master_bypass" ON "public"."monthly_projection"
  AS PERMISSIVE FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER');

-- CREATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "monthly_projection_create" ON "public"."monthly_projection";
CREATE POLICY "monthly_projection_create" ON "public"."monthly_projection"
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- READ: allowed for CEO, ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "monthly_projection_read" ON "public"."monthly_projection";
CREATE POLICY "monthly_projection_read" ON "public"."monthly_projection"
  AS PERMISSIVE FOR SELECT TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('CEO', 'ANALISTA', 'AUXILIAR'));

-- UPDATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "monthly_projection_update" ON "public"."monthly_projection";
CREATE POLICY "monthly_projection_update" ON "public"."monthly_projection"
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- DELETE: allowed for ANALISTA.
DROP POLICY IF EXISTS "monthly_projection_delete" ON "public"."monthly_projection";
CREATE POLICY "monthly_projection_delete" ON "public"."monthly_projection"
  AS PERMISSIVE FOR DELETE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- RLS policies for "public"."credit_facility" (matrix resource: "credit_facility")
ALTER TABLE "public"."credit_facility" ENABLE ROW LEVEL SECURITY;

-- MASTER bypass: a permissive policy granting full access when the JWT's role is MASTER.
DROP POLICY IF EXISTS "credit_facility_master_bypass" ON "public"."credit_facility";
CREATE POLICY "credit_facility_master_bypass" ON "public"."credit_facility"
  AS PERMISSIVE FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER');

-- CREATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "credit_facility_create" ON "public"."credit_facility";
CREATE POLICY "credit_facility_create" ON "public"."credit_facility"
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- READ: allowed for CEO, ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "credit_facility_read" ON "public"."credit_facility";
CREATE POLICY "credit_facility_read" ON "public"."credit_facility"
  AS PERMISSIVE FOR SELECT TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('CEO', 'ANALISTA', 'AUXILIAR'));

-- UPDATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "credit_facility_update" ON "public"."credit_facility";
CREATE POLICY "credit_facility_update" ON "public"."credit_facility"
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- DELETE: allowed for ANALISTA.
DROP POLICY IF EXISTS "credit_facility_delete" ON "public"."credit_facility";
CREATE POLICY "credit_facility_delete" ON "public"."credit_facility"
  AS PERMISSIVE FOR DELETE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- RLS policies for "public"."appraisal" (matrix resource: "appraisal")
ALTER TABLE "public"."appraisal" ENABLE ROW LEVEL SECURITY;

-- MASTER bypass: a permissive policy granting full access when the JWT's role is MASTER.
DROP POLICY IF EXISTS "appraisal_master_bypass" ON "public"."appraisal";
CREATE POLICY "appraisal_master_bypass" ON "public"."appraisal"
  AS PERMISSIVE FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER');

-- CREATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "appraisal_create" ON "public"."appraisal";
CREATE POLICY "appraisal_create" ON "public"."appraisal"
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- READ: allowed for CEO, ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "appraisal_read" ON "public"."appraisal";
CREATE POLICY "appraisal_read" ON "public"."appraisal"
  AS PERMISSIVE FOR SELECT TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('CEO', 'ANALISTA', 'AUXILIAR'));

-- UPDATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "appraisal_update" ON "public"."appraisal";
CREATE POLICY "appraisal_update" ON "public"."appraisal"
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- DELETE: allowed for ANALISTA.
DROP POLICY IF EXISTS "appraisal_delete" ON "public"."appraisal";
CREATE POLICY "appraisal_delete" ON "public"."appraisal"
  AS PERMISSIVE FOR DELETE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- RLS policies for "public"."disbursement" (matrix resource: "disbursement")
ALTER TABLE "public"."disbursement" ENABLE ROW LEVEL SECURITY;

-- MASTER bypass: a permissive policy granting full access when the JWT's role is MASTER.
DROP POLICY IF EXISTS "disbursement_master_bypass" ON "public"."disbursement";
CREATE POLICY "disbursement_master_bypass" ON "public"."disbursement"
  AS PERMISSIVE FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER');

-- CREATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "disbursement_create" ON "public"."disbursement";
CREATE POLICY "disbursement_create" ON "public"."disbursement"
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- READ: allowed for CEO, ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "disbursement_read" ON "public"."disbursement";
CREATE POLICY "disbursement_read" ON "public"."disbursement"
  AS PERMISSIVE FOR SELECT TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('CEO', 'ANALISTA', 'AUXILIAR'));

-- UPDATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "disbursement_update" ON "public"."disbursement";
CREATE POLICY "disbursement_update" ON "public"."disbursement"
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- DELETE: allowed for ANALISTA.
DROP POLICY IF EXISTS "disbursement_delete" ON "public"."disbursement";
CREATE POLICY "disbursement_delete" ON "public"."disbursement"
  AS PERMISSIVE FOR DELETE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- RLS policies for "public"."cap_adjustment" (matrix resource: "cap_adjustment")
ALTER TABLE "public"."cap_adjustment" ENABLE ROW LEVEL SECURITY;

-- MASTER bypass: a permissive policy granting full access when the JWT's role is MASTER.
DROP POLICY IF EXISTS "cap_adjustment_master_bypass" ON "public"."cap_adjustment";
CREATE POLICY "cap_adjustment_master_bypass" ON "public"."cap_adjustment"
  AS PERMISSIVE FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER');

-- CREATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "cap_adjustment_create" ON "public"."cap_adjustment";
CREATE POLICY "cap_adjustment_create" ON "public"."cap_adjustment"
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- READ: allowed for CEO, ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "cap_adjustment_read" ON "public"."cap_adjustment";
CREATE POLICY "cap_adjustment_read" ON "public"."cap_adjustment"
  AS PERMISSIVE FOR SELECT TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('CEO', 'ANALISTA', 'AUXILIAR'));

-- UPDATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "cap_adjustment_update" ON "public"."cap_adjustment";
CREATE POLICY "cap_adjustment_update" ON "public"."cap_adjustment"
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- DELETE: allowed for ANALISTA.
DROP POLICY IF EXISTS "cap_adjustment_delete" ON "public"."cap_adjustment";
CREATE POLICY "cap_adjustment_delete" ON "public"."cap_adjustment"
  AS PERMISSIVE FOR DELETE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- RLS policies for "public"."exchange_rate" (matrix resource: "exchange_rate")
ALTER TABLE "public"."exchange_rate" ENABLE ROW LEVEL SECURITY;

-- MASTER bypass: a permissive policy granting full access when the JWT's role is MASTER.
DROP POLICY IF EXISTS "exchange_rate_master_bypass" ON "public"."exchange_rate";
CREATE POLICY "exchange_rate_master_bypass" ON "public"."exchange_rate"
  AS PERMISSIVE FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER');

-- CREATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "exchange_rate_create" ON "public"."exchange_rate";
CREATE POLICY "exchange_rate_create" ON "public"."exchange_rate"
  AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- READ: allowed for CEO, ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "exchange_rate_read" ON "public"."exchange_rate";
CREATE POLICY "exchange_rate_read" ON "public"."exchange_rate"
  AS PERMISSIVE FOR SELECT TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('CEO', 'ANALISTA', 'AUXILIAR'));

-- UPDATE: allowed for ANALISTA.
DROP POLICY IF EXISTS "exchange_rate_update" ON "public"."exchange_rate";
CREATE POLICY "exchange_rate_update" ON "public"."exchange_rate"
  AS PERMISSIVE FOR UPDATE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- DELETE: allowed for ANALISTA.
DROP POLICY IF EXISTS "exchange_rate_delete" ON "public"."exchange_rate";
CREATE POLICY "exchange_rate_delete" ON "public"."exchange_rate"
  AS PERMISSIVE FOR DELETE TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('ANALISTA'));

-- RLS policies for "public"."audit_log" (matrix resource: "audit_log")
ALTER TABLE "public"."audit_log" ENABLE ROW LEVEL SECURITY;

-- MASTER bypass: a permissive policy granting full access when the JWT's role is MASTER.
DROP POLICY IF EXISTS "audit_log_master_bypass" ON "public"."audit_log";
CREATE POLICY "audit_log_master_bypass" ON "public"."audit_log"
  AS PERMISSIVE FOR ALL TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'MASTER');

-- CREATE: no non-MASTER role allowed by the matrix.
DROP POLICY IF EXISTS "audit_log_create_deny" ON "public"."audit_log";
-- (No CREATE POLICY emitted; absence of a permissive policy implicitly denies.)

-- READ: allowed for CEO, ANALISTA, AUXILIAR.
DROP POLICY IF EXISTS "audit_log_read" ON "public"."audit_log";
CREATE POLICY "audit_log_read" ON "public"."audit_log"
  AS PERMISSIVE FOR SELECT TO authenticated
  USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('CEO', 'ANALISTA', 'AUXILIAR'));

-- UPDATE: no non-MASTER role allowed by the matrix.
DROP POLICY IF EXISTS "audit_log_update_deny" ON "public"."audit_log";
-- (No CREATE POLICY emitted; absence of a permissive policy implicitly denies.)

-- DELETE: no non-MASTER role allowed by the matrix.
DROP POLICY IF EXISTS "audit_log_delete_deny" ON "public"."audit_log";
-- (No CREATE POLICY emitted; absence of a permissive policy implicitly denies.)
